services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306      
      DB_DATABASE: system_engineering_db
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - system_engineering_network

  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    networks:
      - system_engineering_network

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: system_engineering_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - system_engineering_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORDd}
    depends_on:
      - db
    networks:
      - system_engineering_network

volumes:
  db_data:

networks:
  system_engineering_network:
